import { NextResponse } from "next/server";
import { PDFDocument, StandardFonts } from "pdf-lib";

export async function POST(
    request: Request
) {

    const body =
    await request.json();

    const pdfDoc =
        await PDFDocument.create();

    const page =
        pdfDoc.addPage([600, 800]);

    const font =
        await pdfDoc.embedFont(
            StandardFonts.Helvetica
        );

        page.drawText(
            "AEGILUX",
            {
                x: 50,
                y: 760,
                size: 28,
                font,
            }
        );

        page.drawText(
            "Security Intelligence Platform",
            {
                x: 50,
                y: 735,
                size: 12,
                font,
            }
        );

        page.drawText(
            "TARGET INFORMATION",
            {
                x: 50,
                y: 700,
                size: 14,
                font,
            }
        );


        page.drawText(
            `IP: ${body.ip}`,
            {
                x: 50,
                y: 670,
                size: 12,
                font,
            }
        );

        page.drawText(
            `Country: ${body.country}`,
            {
                x: 50,
                y: 650,
                size: 12,
                font,
            }
        );

        page.drawText(
            `ISP: ${body.isp}`,
            {
                x: 50,
                y: 630,
                size: 12,
                font,
            }
        );

        page.drawText(
            "SECURITY ASSESSMENT",
            {
                x: 50,
                y: 590,
                size: 14,
                font,
            }
        );


        page.drawText(
            `Threat Score: ${body.threatScore}/100`,
            {
                x: 50,
                y: 560,
                size: 12,
                font,
            }
        );

        page.drawText(
            "SSL INTELLIGENCE",
            {
                x: 50,
                y: 520,
                size: 14,
                font,
            }
        );

        page.drawText(
            `SSL Issuer: ${body.sslIssuer}`,
            {
                x: 50,
                y: 400,
                size: 12,
                font,
            }
        );

        page.drawText(
            `SSL Expires: ${body.sslExpires}`,
            {
                x: 50,
                y: 470,
                size: 12,
                font,
            }
        );

        page.drawText(
            `SSL Risk: ${body.sslRisk}`,
            {
                x: 50,
                y: 450,
                size: 12,
                font,
            }
        );

        page.drawText(
            "Generated by Aegilux Security Platform",
            {
                x: 50,
                y: 50,
                size: 10,
                font,
            }
        );

        const pdfBytes =
            await pdfDoc.save();

        return new NextResponse(
            Buffer.from(pdfBytes),
            {
                headers: {
                    "Content-Type":
                    "application/pdf",
                    "Content-Disposition":
                    'attachment; filename="aegilux-report.pdf"',
                },
            }
        );
}